### ISSUE TITLE
Question during training

### ISSUE THREAD

**Issue by louhz** [tijiang13/InstantAvatar#10]
HI, I just face some issue during the training 

The entire log is showed below:

 HYDRA_FULL_ERROR=1 srun -t 0-5 -G 1 bash ./bash/run-neuman-demo.sh
srun: job 3593 queued and waiting for resources
srun: job 3593 has been allocated resources
fit.py:14: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="./confs", config_name="SNARF_NGP_fitting")
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[rank: 0] Global seed set to 42
Switch to /DATA_EDS/louhz/semanticnerf/InstantAvatar/outputs/neuman/baseline/seattle
[train] No optimized smpl found.
[val] No optimized smpl found.
[test] No optimized smpl found.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/pytorch_lightning/profiler/__init__.py:27: LightningDeprecationWarning: `pytorch_lightning.profiler.AdvancedProfiler` is deprecated in v1.9.0 and will be removed in v2.0.0. Use the equivalent `pytorch_lightning.profilers.AdvancedProfiler` class instead.
  rank_zero_deprecation(
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:478: LightningDeprecationWarning: Setting `Trainer(gpus=1)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=1)` instead.
  rank_zero_deprecation(
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/lightning_fabric/plugins/environments/slurm.py:166: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python fit.py --config-name SNARF_NGP_fitting dataset=neuma ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type               | Params
--------------------------------------------------
0 | net_coarse | NeRFNGPNet         | 13.0 M
1 | SMPL_param | SMPLParamEmbedding | 3.1 K 
2 | loss_fn    | NGPLoss            | 14.7 M
3 | evaluator  | Evaluator          | 2.5 M 
--------------------------------------------------
13.0 M    Trainable params
17.2 M    Non-trainable params
30.2 M    Total params
120.905   Total estimated model params size (MB)
Saving configs.
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1609: PossibleUserWarning: The number of training batches (41) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Epoch 499: 100%|██████████| 42/42 [00:03<00:00, 11.58it/s, v_num=0]
Epoch 499: 100%|██████████| 42/42 [00:03<00:00, 11.57it/s, v_num=0]/s]
Save optimized pose to /DATA_EDS/louhz/semanticnerf/InstantAvatar/data/custom/seattle/poses/train.npz
train.py:12: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="./confs", config_name="SNARF_NGP")
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[rank: 0] Global seed set to 42
Switch to /DATA_EDS/louhz/semanticnerf/InstantAvatar/outputs/neuman/baseline/seattle
[train] Loading from /DATA_EDS/louhz/semanticnerf/InstantAvatar/data/custom/seattle/poses/train.npz
[val] No optimized smpl found.
[test] No optimized smpl found.
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/pytorch_lightning/profiler/__init__.py:27: LightningDeprecationWarning: `pytorch_lightning.profiler.AdvancedProfiler` is deprecated in v1.9.0 and will be removed in v2.0.0. Use the equivalent `pytorch_lightning.profilers.AdvancedProfiler` class instead.
  rank_zero_deprecation(
WARNING: You are using a SMPL model, with only 10 shape coefficients.
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:478: LightningDeprecationWarning: Setting `Trainer(gpus=1)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=1)` instead.
  rank_zero_deprecation(
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/lightning_fabric/plugins/environments/slurm.py:166: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python train.py --config-name demo dataset=neuman/seattle e ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type       | Params
------------------------------------------
0 | net_coarse | NeRFNGPNet | 13.0 M
1 | loss_fn    | NGPLoss    | 14.7 M
2 | evaluator  | Evaluator  | 2.5 M 
------------------------------------------
13.0 M    Trainable params
17.2 M    Non-trainable params
30.2 M    Total params
120.893   Total estimated model params size (MB)
Saving configs.
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1609: PossibleUserWarning: The number of training batches (41) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Epoch 199: 100%|██████████| 42/42 [00:03<00:00, 13.41it/s, v_num=0]
`Trainer.fit` stopped: `max_epochs=200` reached.0:00<00:00,  1.52it/s]
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Epoch 199: 100%|██████████| 42/42 [00:03<00:00, 13.39it/s, v_num=0]
Testing DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  4.81it/s]   
novel_view.py:91: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="./confs", config_name="SNARF_NGP")
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[rank: 0] Global seed set to 42
Switch to /DATA_EDS/louhz/semanticnerf/InstantAvatar/outputs/neuman/baseline/seattle
[train] Loading from /DATA_EDS/louhz/semanticnerf/InstantAvatar/data/custom/seattle/poses/train.npz
[val] No optimized smpl found.
[test] No optimized smpl found.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Error executing job with overrides: ['dataset=neuman/seattle', 'experiment=baseline', 'deformer.opt.cano_pose=a_pose']
Traceback (most recent call last):
  File "novel_view.py", line 132, in <module>
    main()
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "novel_view.py", line 103, in main
    print("Resume from", checkpoints[-1])
IndexError: list index out of range
animate.py:81: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="./confs", config_name="SNARF_NGP")
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[rank: 0] Global seed set to 42
Switch to /DATA_EDS/louhz/semanticnerf/InstantAvatar/outputs/neuman/baseline/seattle
[train] Loading from /DATA_EDS/louhz/semanticnerf/InstantAvatar/data/custom/seattle/poses/train.npz
[val] No optimized smpl found.
[test] No optimized smpl found.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Error executing job with overrides: ['dataset=neuman/seattle', 'experiment=baseline', 'deformer.opt.cano_pose=a_pose']
Traceback (most recent call last):
  File "animate.py", line 121, in <module>
    main()
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/DATA_EDS/louhz/anaconda3/envs/anerf/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "animate.py", line 93, in main
    print("Resume from", checkpoints[-1])
IndexError: list index out of range
srun: error: discover-02: task 0: Exited with exit code 1

**Comment by louhz** [comment]
It looks like the issue raised from the loading of checkpoints. But i am not familiar with hydra and not sure how to solve this issue

**Comment by tijiang13** [comment]
> It looks like the issue raised from the loading of checkpoints. But i am not familiar with hydra and not sure how to solve this issue

Yes, it looks for some reason the program cannot find the checkpoints. Can you check if there is any checkpoint in the outputs folder? If not, maybe you need to consult the IT department.

**Comment by louhz** [comment]
> > It looks like the issue raised from the loading of checkpoints. But i am not familiar with hydra and not sure how to solve this issue
> 
> Yes, it looks for some reason the program cannot find the checkpoints. Can you check if there is any checkpoint in the outputs folder? If not, maybe you need to consult the IT department.

So there is no checkpoint in the outputs folder and I will try to fix it. Thanks!

**Comment by fual810** [comment]
I have a same problem. Could you tell me how to fix it.

**Comment by GUI0809** [comment]
> I have a same problem. Could you tell me how to fix it.
Hello, have you got the solution, I have the same problem as you?

**Comment by ShenghaoJia** [comment]
I encountered the issue of checkpoints not being saved during training as well. Ultimately, I discovered that it was caused by an incorrect version of PyTorch Lightning (due to my GPU architecture, I did not follow the version specified in install.sh). After downgrading PyTorch Lightning to version 1.5.7, this problem was resolved.
