### ISSUE TITLE
How to use own video to run "bash scripts/custom/process-sequence.sh"?

### ISSUE THREAD

**Issue by nick8592** [tijiang13/InstantAvatar#13]
Hello, 
To begin with, I want to convey my profound gratitude for your remarkable efforts. Now I'm using my own video to proceed on "Play with Your Own Video" step 3. run the bash script bash scripts/custom/process-sequence.sh ./data/custom/seattle neutral to preprocess the images. But now I've an error message as below:
```
root@e621618f3def:/instant# bash scripts/custom/process-sequence.sh ./data/custom/mmlab neutral
Running OpenPose in /instant/data/custom/mmlab/images
scripts/custom/run-openpose-bin.sh: line 23: cd: scripts/custom/run-openpose-bin.sh/openpose/3rdparty: Not a directory
scripts/custom/run-openpose-bin.sh: line 25: ./build/examples/openpose/openpose.bin: No such file or directory
Traceback (most recent call last):
  File "/instant/./scripts/custom/convert_openpose_json_to_npy.py", line 44, in <module>
    convert(JSON_FOLDER, NPY_PATH)
  File "/instant/./scripts/custom/convert_openpose_json_to_npy.py", line 11, in convert
    for JSON_FILE in sorted(os.listdir(JSON_FOLDER)):
FileNotFoundError: [Errno 2] No such file or directory: '/instant/data/custom/mmlab/images/../openpose_json/'
```
It seems like it can not find my `openpose` folder, but in your file `scripts\custom\run-openpose-bin.sh` at [line 15](https://github.com/tijiang13/InstantAvatar/blob/212d5445e9c1b093c4c1ec0845b12ccf00c68729/scripts/custom/run-openpose-bin.sh#L15) said that I need to replace the `OPENPOSE_PATH` to my local openpose folder. My `openpose` folder I placed in `<workspace_folder>/openpose`.
However, I can not find the `third_party/openpose-cpp` folder in my local `openpose` folder. How should I do to resolve this issue or how can I replace the `OPENPOSE_PATH` based on the files that current exist in my local `openpose` folder?
The folder structure show as below:
```
\<workspace_folder\>
    ├── bash
    ├── confs
    ├── data
    ├── dataset
    ├── env
    ├── instabt_avatar
    ├── media
    ├── openpose
    │   ├── 3rdparty
    │   │   ├── windows
    │   │   │   ├── unzip
    │   │   │   └── wget
    │   │   └── Versions.txt
    │   ├── bin
    │   ├── examples
    │   ├── include
    │   ├── lib
    │   ├── models
    │   └── python
    ├──outputs
    ├──pytorch3d
    ├──scripts
...
    └── README.md
```

**Comment by tijiang13** [comment]
Hi Nick,

Yes, you're right. `openpose.bin` is the binary you got after compiling. You can use following script to build it:

```bash
# assuming you are in the openpose folder
mkdir build
cd build & cmake ..
make -j8
```

You may encounter some errors if some dependencies are missing, in which case you may need to refer [the official document](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md#compiling-and-running-openpose-from-source).

Best,
Tianjian
