### ISSUE TITLE
Why it take many epochs while evaluating ?

### ISSUE THREAD

**Issue by Miles629** [tijiang13/InstantAvatar#14]
Hi, Dr. Jiang.
I tried the code, and it trained really fast!
I am evaluating the trained model and have some questions about the process. 
1, Why is it need to optimize the SMPL parameters during the evaluation? 
2, Does this meet the evaluation standards?  (I have some concerns regarding optimizing SMPL parameters during evaluation, which may involve utilizing the target image, even though it is only used for parameter optimization purposes. While I acknowledge the importance of this practice for improving the metrics, as the SMPL provided in the dataset may not be entirely accurate, I am concerned about the validity of the results. Nonetheless, I still believe that InstantAvatar is a highly effective approach.)

**Comment by tijiang13** [comment]
Hi Caoyuan,

1. Because the SMPL provided is not accurate.
2. We follow our baselines. See: https://github.com/JanaldoChen/Anim-NeRF#training

Best,
Tianjian
