### ISSUE TITLE
I visualize the pts before and after the deformation and found its very strange

### ISSUE THREAD

**Issue by sora158** [tijiang13/InstantAvatar#18]
pts_cano_all, valid = self.deform(pts.type(self.dtype), eval_mode=False)
 I visualize the pts and  pts_cano_all[valid]
 what I supposed pts and pts_cano_all[valid] is a deformed human limbs and canonical human A pose, but It looks like below:
![DP%9XFJ7`O$ITB8 PO~VU8K](https://github.com/tijiang13/InstantAvatar/assets/51376780/11e5299c-14a7-4891-88d7-d14448df8a3a)

Please tell me the reason, thank you!

**Comment by sora158** [comment]
![DP%9XFJ7`O$ITB8 PO~VU8K](https://github.com/tijiang13/InstantAvatar/assets/51376780/a34724d5-d4e4-4bd2-84ab-612b8759d3be)
before
![T$49VA(P`BH FSVV)EM9RH8](https://github.com/tijiang13/InstantAvatar/assets/51376780/f19c4dd0-2e35-45d1-b293-7953eca0c569)
after

**Comment by tijiang13** [comment]
> > Hi Sora,
> > Which sequence are you running?
> > Best, Tianjian
> 
> Thank you, I'm running on sequence male-3-causal

Are you visualizing the deformed points during the training phase? If so, could you let me know the number of epochs you're planning to visualize? It's worth noting that if the training has just begun, it may take some time to converge.

Best, Tianjian

**Comment by sora158** [comment]
> > Hi Sora,
> > 
> > Which sequence are you running?
> > 
> > Best, Tianjian
> 
> Thank you, I'm running on sequence male-3-causal

I visualize it in 10~20 epochs, and it shows the same. the total is 30 epochs, so I feel confused. Maybe it have the relations to the raysampling method?

**Comment by tijiang13** [comment]
Hi Sora,

I just gave it a check and that's what I got:

<img width="720" alt="image" src="https://github.com/tijiang13/InstantAvatar/assets/15152165/7bb974da-31d6-400f-b963-4515f21af47d">

In SNARF, we initially deform the points using several candidate transformations, but only the ones with the highest confidence are retained. However, the points you currently have are before filtering and may contain a significant amount of noise, which will be filtered out in a subsequent stage.

Best, Tianjian

**Comment by sora158** [comment]
Thank you for your reply, I will learn how it get filtered later. Thank for yours' excellent work.
