### ISSUE TITLE
Code question: empty space skipping

### ISSUE THREAD

**Issue by Miles629** [tijiang13/InstantAvatar#20]
Hello Dr. Jiang. 
I'm not sure which part of the code implements the empty space skipping. This module seems to play a crucial role in reducing training and  rendering time.
I guess it is the code shown below that provides the mask to reduce the number of sampling points for subsequent computations. However, this code only exists in render_test, so can we assume that the speed improvement during training is due to the improvement in validation speed?
```
pts, d_new, z_new = raymarch_kernel.raymarch_test(rays_o, rays_d, near, far, alive,
                                                              density_grid.density_field, scale, offset,
                                                              step_size, N_step)
            
            
counter[alive] += (d_new > 0).sum(dim=-1)
mask = d_new > 0
```
In fact, I also tried to filter unnecessary sampling points to improve speed. However, the performance of empty space skipping is superior and outstanding.

BTW, I run the code and find that it will get slightly better result by using smpl deformer.  In addition, using NeRFLoss is more helpful in imporving PSNR, RGBLoss and SSIM.
In contrast, the SNARF deformer has a significant effect on improving speed. Using a 3090ti, I can achieve a maximum iteration speed of 40iter/s. An outstanding job!

**Comment by tijiang13** [comment]
Hi Caoyuan,

If you are looking for the skipping part, we do that for both training and inference. You can check [L101](https://github.com/tijiang13/InstantAvatar/blob/master/instant_avatar/renderers/raymarcher_acc.py#L101) and [L141](https://github.com/tijiang13/InstantAvatar/blob/master/instant_avatar/renderers/raymarcher_acc.py#L141).

Best,
Tianjian

**Comment by Miles629** [comment]
Thank you for your prompt response.
 In the NeRF method, we usually consider `z_val` as the sampling distance. In ` mask = z_vals > 0`, the removal of values with `z_val` less than or equal to 0 is easy to understand.
But I am not familiar with the CUDA code. I still have some questions:
1. If there is a special design for obtaining `z_val` in [L141](https://github.com/tijiang13/InstantAvatar/blob/master/instant_avatar/renderers/raymarcher_acc.py#L141)? 
2. Is the code `raymarch_train_cuda`[L164](https://github.com/tijiang13/InstantAvatar/blob/212d5445e9c1b093c4c1ec0845b12ccf00c68729/instant_avatar/renderers/cuda/raymarcher.cu#L164) being called here? It seems hard to understand. Could you please point out the specific location where the code is being called?
Yours,
Cy

**Comment by tijiang13** [comment]
Hi Caoyuan,

1. Here we just extract the z_vals because we want to utilise the auto-diff of torch.
2. It's called in [L141](https://github.com/tijiang13/InstantAvatar/blob/master/instant_avatar/renderers/raymarcher_acc.py#L141) via pybindings

Best,
Tianjian

**Comment by Miles629** [comment]
Thank you, I will take another look at the code.
