### ISSUE TITLE
Error in "scripts/visualize-SMPL.py"

### ISSUE THREAD

**Issue by mch0dmin** [tijiang13/InstantAvatar#21]
Run the following command：
```
python scripts/visualize-SMPL.py --path ./data/custom/seattle --gender neutral --pose ./data/custom/seattle/pose_optimized.npz --headless --fps 1
```

Error log :

```
Traceback (most recent call last):
  File "scripts/visualize-SMPL.py", line 121, in <module>
    smpl_layer = SMPLLayer(model_type='smpl',
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/aitviewer/models/smpl.py", line 66, in __init__
    self.bm = smplx.create(
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/smplx/body_models.py", line 2412, in create
    return SMPLX(model_path, **kwargs)
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/smplx/body_models.py", line 975, in __init__
    assert osp.exists(smplx_path), 'Path {} does not exist!'.format(smplx_path)
AssertionError: Path ../data/smplx_models does not exist!
```

Setting the following directory structure is still incorrect ：

```
$ tree data/smplx_models/
data/smplx_models/
├── mano
│   ├── MANO_LEFT.pkl
│   └── MANO_RIGHT.pkl
├── smpl
│   ├── SMPL_FEMALE.pkl
│   ├── SMPL_MALE.pkl
│   └── SMPL_NEUTRAL.pkl
├── smplh
│   ├── SMPLH_female.pkl
│   └── SMPLH_male.pkl
└── smplx
    ├── SMPLX_FEMALE.npz
    ├── SMPLX_FEMALE.pkl
    ├── SMPLX_MALE.npz
    ├── SMPLX_MALE.pkl
    ├── SMPLX_NEUTRAL.npz
    └── SMPLX_NEUTRAL.pkl

4 directories, 13 files

```

**Comment by tijiang13** [comment]
Hi,

The aitviewer needs to be configure separately. You can change the path of SMPL in the `https://github.com/eth-ait/aitviewer/blob/main/aitviewer/aitvconfig.yaml`

Best,
Tianjian

**Comment by mch0dmin** [comment]
> Hi,
> 
> The aitviewer needs to be configured separately. You can change the path of SMPL in the `https://github.com/eth-ait/aitviewer/blob/main/aitviewer/aitvconfig.yaml`
> 
> Best, Tianjian

Thank you for your reply. I will try and provide feedback on the results.

**Comment by Net-Maker** [comment]
Meet the same problem.
Have you solved this?

**Comment by litchisea** [comment]
Hello, I solved the error according to the answer, but a new error appeared, did you encounter it and have a solution?
<img width="755" alt="914642c941835dc7b0f3980766c4def" src="https://github.com/tijiang13/InstantAvatar/assets/106635715/1a91ee8c-5a70-4cfc-ad51-ce02fb7009e1">

**Comment by Net-Maker** [comment]
> Hello, I solved the error according to the answer, but a new error appeared, did you encounter it and have a solution? <img alt="914642c941835dc7b0f3980766c4def" width="755" src="https://user-images.githubusercontent.com/106635715/251692287-1a91ee8c-5a70-4cfc-ad51-ce02fb7009e1.png">
As you can see,the frame number is 0.Maybe your SAM or ROMP or OPENPOSE do not work .

**Comment by yoshua133** [comment]
> > Hello, I solved the error according to the answer, but a new error appeared, did you encounter it and have a solution? <img alt="914642c941835dc7b0f3980766c4def" width="755" src="https://user-images.githubusercontent.com/106635715/251692287-1a91ee8c-5a70-4cfc-ad51-ce02fb7009e1.png">
> > As you can see,the frame number is 0.Maybe your SAM or ROMP or OPENPOSE do not work .

Hi, I have encountered the same problem. I have checked the masks directory and images directory. They seems to be good. And I have checked the output video of openpose, it works too. And the output of the smpl parameter from ROMP seems not to have strange values.  

But the frames in viewer is 0. Do you know what other reason might cause the problem? Or how can I check the output of ROMP?

Thank you very much!

**Comment by Net-Maker** [comment]
> > > Hello, I solved the error according to the answer, but a new error appeared, did you encounter it and have a solution? <img alt="914642c941835dc7b0f3980766c4def" width="755" src="https://user-images.githubusercontent.com/106635715/251692287-1a91ee8c-5a70-4cfc-ad51-ce02fb7009e1.png">
> > > As you can see,the frame number is 0.Maybe your SAM or ROMP or OPENPOSE do not work .
> 
> Hi, I have encountered the same problem. I have checked the masks directory and images directory. They seems to be good. And I have checked the output video of openpose, it works too. And the output of the smpl parameter from ROMP seems not to have strange values.
> 
> But the frames in viewer is 0. Do you know what other reason might cause the problem? Or how can I check the output of ROMP?
> 
> Thank you very much!

You can check the "pose.npz",which is created by ROMP,and "poses_optimized",which is created by "refine_SMPL.py".The "Visualize_SMPL.py" read the "poses_optimized" and use aitviewer to visualize it automaticly,so make sure your aitviewer work smoothly.
And you can load the file "poses.npz" by using numpy,and print the parameters'shape to check.
By the way,you can try to delete all files in your data directory except the images directory and run the preprocess again if SAM,ROMP and OPENPOSE work properly.
If you are insure that your parameters are all right,try to the render setp directly,there are some problems in this "visualizeSMPL.py"

**Comment by yoshua133** [comment]
> > > > Hello, I solved the error according to the answer, but a new error appeared, did you encounter it and have a solution? <img alt="914642c941835dc7b0f3980766c4def" width="755" src="https://user-images.githubusercontent.com/106635715/251692287-1a91ee8c-5a70-4cfc-ad51-ce02fb7009e1.png">
> > > > As you can see,the frame number is 0.Maybe your SAM or ROMP or OPENPOSE do not work .
> > 
> > 
> > Hi, I have encountered the same problem. I have checked the masks directory and images directory. They seems to be good. And I have checked the output video of openpose, it works too. And the output of the smpl parameter from ROMP seems not to have strange values.
> > But the frames in viewer is 0. Do you know what other reason might cause the problem? Or how can I check the output of ROMP?
> > Thank you very much!
> 
> You can check the "pose.npz",which is created by ROMP,and "poses_optimized",which is created by "refine_SMPL.py".The "Visualize_SMPL.py" read the "poses_optimized" and use aitviewer to visualize it automaticly,so make sure your aitviewer work smoothly. And you can load the file "poses.npz" by using numpy,and print the parameters'shape to check. By the way,you can try to delete all files in your data directory except the images directory and run the preprocess again if SAM,ROMP and OPENPOSE work properly. If you are insure that your parameters are all right,try to the render setp directly,there are some problems in this "visualizeSMPL.py"

I have removed the "--headless" arg. It opened the ativiewer window and seemed to work.  
![Screen Shot 2023-07-09 at 7 10 15 PM](https://github.com/tijiang13/InstantAvatar/assets/39624548/0ffb7d53-ddfd-45e6-80f8-c5d26cf1c611)

**Comment by vrahnos3** [comment]
> > > > > Hello, I solved the error according to the answer, but a new error appeared, did you encounter it and have a solution? <img alt="914642c941835dc7b0f3980766c4def" width="755" src="https://user-images.githubusercontent.com/106635715/251692287-1a91ee8c-5a70-4cfc-ad51-ce02fb7009e1.png">
> > > > > As you can see,the frame number is 0.Maybe your SAM or ROMP or OPENPOSE do not work .
> > > 
> > > 
> > > Hi, I have encountered the same problem. I have checked the masks directory and images directory. They seems to be good. And I have checked the output video of openpose, it works too. And the output of the smpl parameter from ROMP seems not to have strange values.
> > > But the frames in viewer is 0. Do you know what other reason might cause the problem? Or how can I check the output of ROMP?
> > > Thank you very much!
> > 
> > 
> > You can check the "pose.npz",which is created by ROMP,and "poses_optimized",which is created by "refine_SMPL.py".The "Visualize_SMPL.py" read the "poses_optimized" and use aitviewer to visualize it automaticly,so make sure your aitviewer work smoothly. And you can load the file "poses.npz" by using numpy,and print the parameters'shape to check. By the way,you can try to delete all files in your data directory except the images directory and run the preprocess again if SAM,ROMP and OPENPOSE work properly. If you are insure that your parameters are all right,try to the render setp directly,there are some problems in this "visualizeSMPL.py"
> 
> I have removed the "--headless" arg. It opened the ativiewer window and seemed to work. ![Screen Shot 2023-07-09 at 7 10 15 PM](https://user-images.githubusercontent.com/39624548/252179249-0ffb7d53-ddfd-45e6-80f8-c5d26cf1c611.png)

Hello, your comment seems to be very usefull. However I received another error when I removed ``--headless`` argument.
Have you any idea what causes this error?
![Screenshot from 2023-11-07 14-59-36](https://github.com/tijiang13/InstantAvatar/assets/63507675/98a0a5af-cceb-4830-8da8-a3a6486b7de0)

**Comment by bayunCC** [comment]
> > > > > > Hello, I solved the error according to the answer, but a new error appeared, did you encounter it and have a solution? <img alt="914642c941835dc7b0f3980766c4def" width="755" src="https://user-images.githubusercontent.com/106635715/251692287-1a91ee8c-5a70-4cfc-ad51-ce02fb7009e1.png">
> > > > > > As you can see,the frame number is 0.Maybe your SAM or ROMP or OPENPOSE do not work .
> > > > 
> > > > 
> > > > Hi, I have encountered the same problem. I have checked the masks directory and images directory. They seems to be good. And I have checked the output video of openpose, it works too. And the output of the smpl parameter from ROMP seems not to have strange values.
> > > > But the frames in viewer is 0. Do you know what other reason might cause the problem? Or how can I check the output of ROMP?
> > > > Thank you very much!
> > > 
> > > 
> > > You can check the "pose.npz",which is created by ROMP,and "poses_optimized",which is created by "refine_SMPL.py".The "Visualize_SMPL.py" read the "poses_optimized" and use aitviewer to visualize it automaticly,so make sure your aitviewer work smoothly. And you can load the file "poses.npz" by using numpy,and print the parameters'shape to check. By the way,you can try to delete all files in your data directory except the images directory and run the preprocess again if SAM,ROMP and OPENPOSE work properly. If you are insure that your parameters are all right,try to the render setp directly,there are some problems in this "visualizeSMPL.py"
> > 
> > 
> > I have removed the "--headless" arg. It opened the ativiewer window and seemed to work. ![Screen Shot 2023-07-09 at 7 10 15 PM](https://user-images.githubusercontent.com/39624548/252179249-0ffb7d53-ddfd-45e6-80f8-c5d26cf1c611.png)
> 
> Hello, your comment seems to be very usefull. However I received another error when I removed `--headless` argument. Have you any idea what causes this error? ![Screenshot from 2023-11-07 14-59-36](https://private-user-images.githubusercontent.com/63507675/281045488-98a0a5af-cceb-4830-8da8-a3a6486b7de0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODU1OTYsIm5iZiI6MTcxMjg4NTI5NiwicGF0aCI6Ii82MzUwNzY3NS8yODEwNDU0ODgtOThhMGE1YWYtY2NlYi00ODMwLThkYTgtYTNhNjQ4NmI3ZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAxMjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NWE4MGQ2ZGY1N2E0YjJkNDk5ZDMzOTk2MmQ4NDc4NjQ3YmI5MGZlZmMxZDU0N2VjM2U4MjYzNjEwYWQwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SVzNvdQJo-NxP0qZQjSj14DkNCmukaMdqCYiQ_0o1Hw)

How did you solve the problem of “no qt platform could be initialized” when remove “--headless” in script.I encountered the same error information like you photo.

**Comment by bayunCC** [comment]
> > > > > > > Hello, I solved the error according to the answer, but a new error appeared, did you encounter it and have a solution? <img alt="914642c941835dc7b0f3980766c4def" width="755" src="https://user-images.githubusercontent.com/106635715/251692287-1a91ee8c-5a70-4cfc-ad51-ce02fb7009e1.png">
> > > > > > > As you can see,the frame number is 0.Maybe your SAM or ROMP or OPENPOSE do not work .
> > > > > 
> > > > > 
> > > > > Hi, I have encountered the same problem. I have checked the masks directory and images directory. They seems to be good. And I have checked the output video of openpose, it works too. And the output of the smpl parameter from ROMP seems not to have strange values.
> > > > > But the frames in viewer is 0. Do you know what other reason might cause the problem? Or how can I check the output of ROMP?
> > > > > Thank you very much!
> > > > 
> > > > 
> > > > You can check the "pose.npz",which is created by ROMP,and "poses_optimized",which is created by "refine_SMPL.py".The "Visualize_SMPL.py" read the "poses_optimized" and use aitviewer to visualize it automaticly,so make sure your aitviewer work smoothly. And you can load the file "poses.npz" by using numpy,and print the parameters'shape to check. By the way,you can try to delete all files in your data directory except the images directory and run the preprocess again if SAM,ROMP and OPENPOSE work properly. If you are insure that your parameters are all right,try to the render setp directly,there are some problems in this "visualizeSMPL.py"
> > > 
> > > 
> > > I have removed the "--headless" arg. It opened the ativiewer window and seemed to work. ![Screen Shot 2023-07-09 at 7 10 15 PM](https://user-images.githubusercontent.com/39624548/252179249-0ffb7d53-ddfd-45e6-80f8-c5d26cf1c611.png)
> > 
> > 
> > Hello, your comment seems to be very usefull. However I received another error when I removed `--headless` argument. Have you any idea what causes this error? ![Screenshot from 2023-11-07 14-59-36](https://private-user-images.githubusercontent.com/63507675/281045488-98a0a5af-cceb-4830-8da8-a3a6486b7de0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODU1OTYsIm5iZiI6MTcxMjg4NTI5NiwicGF0aCI6Ii82MzUwNzY3NS8yODEwNDU0ODgtOThhMGE1YWYtY2NlYi00ODMwLThkYTgtYTNhNjQ4NmI3ZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAxMjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NWE4MGQ2ZGY1N2E0YjJkNDk5ZDMzOTk2MmQ4NDc4NjQ3YmI5MGZlZmMxZDU0N2VjM2U4MjYzNjEwYWQwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SVzNvdQJo-NxP0qZQjSj14DkNCmukaMdqCYiQ_0o1Hw)
> 
> How did you solve the problem of “no qt platform could be initialized” when remove “--headless” in script.I encountered the same error information like you photo.

I have solve this problem.I uninstall my opencv-python in my anaconda environment and install opencv-python-headless=4.6.0.66 instead.It is necessary to install specific version, I use opencv4.9 is unable to run, some functions have changed in higher version.

**Comment by bayunCC** [comment]
> > > > > > > > Hello, I solved the error according to the answer, but a new error appeared, did you encounter it and have a solution? <img alt="914642c941835dc7b0f3980766c4def" width="755" src="https://user-images.githubusercontent.com/106635715/251692287-1a91ee8c-5a70-4cfc-ad51-ce02fb7009e1.png">
> > > > > > > > As you can see,the frame number is 0.Maybe your SAM or ROMP or OPENPOSE do not work .
> > > > > > 
> > > > > > 
> > > > > > Hi, I have encountered the same problem. I have checked the masks directory and images directory. They seems to be good. And I have checked the output video of openpose, it works too. And the output of the smpl parameter from ROMP seems not to have strange values.
> > > > > > But the frames in viewer is 0. Do you know what other reason might cause the problem? Or how can I check the output of ROMP?
> > > > > > Thank you very much!
> > > > > 
> > > > > 
> > > > > You can check the "pose.npz",which is created by ROMP,and "poses_optimized",which is created by "refine_SMPL.py".The "Visualize_SMPL.py" read the "poses_optimized" and use aitviewer to visualize it automaticly,so make sure your aitviewer work smoothly. And you can load the file "poses.npz" by using numpy,and print the parameters'shape to check. By the way,you can try to delete all files in your data directory except the images directory and run the preprocess again if SAM,ROMP and OPENPOSE work properly. If you are insure that your parameters are all right,try to the render setp directly,there are some problems in this "visualizeSMPL.py"
> > > > 
> > > > 
> > > > I have removed the "--headless" arg. It opened the ativiewer window and seemed to work. ![Screen Shot 2023-07-09 at 7 10 15 PM](https://user-images.githubusercontent.com/39624548/252179249-0ffb7d53-ddfd-45e6-80f8-c5d26cf1c611.png)
> > > 
> > > 
> > > Hello, your comment seems to be very usefull. However I received another error when I removed `--headless` argument. Have you any idea what causes this error? ![Screenshot from 2023-11-07 14-59-36](https://private-user-images.githubusercontent.com/63507675/281045488-98a0a5af-cceb-4830-8da8-a3a6486b7de0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODU1OTYsIm5iZiI6MTcxMjg4NTI5NiwicGF0aCI6Ii82MzUwNzY3NS8yODEwNDU0ODgtOThhMGE1YWYtY2NlYi00ODMwLThkYTgtYTNhNjQ4NmI3ZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAxMjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NWE4MGQ2ZGY1N2E0YjJkNDk5ZDMzOTk2MmQ4NDc4NjQ3YmI5MGZlZmMxZDU0N2VjM2U4MjYzNjEwYWQwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SVzNvdQJo-NxP0qZQjSj14DkNCmukaMdqCYiQ_0o1Hw)
> > 
> > 
> > How did you solve the problem of “no qt platform could be initialized” when remove “--headless” in script.I encountered the same error information like you photo.
> 
> I have solve this problem.I uninstall my opencv-python in my anaconda environment and install opencv-python-headless=4.6.0.66 instead.It is necessary to install specific version, I use opencv4.9 is unable to run, some functions have changed in higher version.



> > > > > > > Hello, I solved the error according to the answer, but a new error appeared, did you encounter it and have a solution? <img alt="914642c941835dc7b0f3980766c4def" width="755" src="https://user-images.githubusercontent.com/106635715/251692287-1a91ee8c-5a70-4cfc-ad51-ce02fb7009e1.png">
> > > > > > > As you can see,the frame number is 0.Maybe your SAM or ROMP or OPENPOSE do not work .
> > > > > 
> > > > > 
> > > > > Hi, I have encountered the same problem. I have checked the masks directory and images directory. They seems to be good. And I have checked the output video of openpose, it works too. And the output of the smpl parameter from ROMP seems not to have strange values.
> > > > > But the frames in viewer is 0. Do you know what other reason might cause the problem? Or how can I check the output of ROMP?
> > > > > Thank you very much!
> > > > 
> > > > 
> > > > You can check the "pose.npz",which is created by ROMP,and "poses_optimized",which is created by "refine_SMPL.py".The "Visualize_SMPL.py" read the "poses_optimized" and use aitviewer to visualize it automaticly,so make sure your aitviewer work smoothly. And you can load the file "poses.npz" by using numpy,and print the parameters'shape to check. By the way,you can try to delete all files in your data directory except the images directory and run the preprocess again if SAM,ROMP and OPENPOSE work properly. If you are insure that your parameters are all right,try to the render setp directly,there are some problems in this "visualizeSMPL.py"
> > > 
> > > 
> > > I have removed the "--headless" arg. It opened the ativiewer window and seemed to work. ![Screen Shot 2023-07-09 at 7 10 15 PM](https://user-images.githubusercontent.com/39624548/252179249-0ffb7d53-ddfd-45e6-80f8-c5d26cf1c611.png)
> > 
> > 
> > Hello, your comment seems to be very usefull. However I received another error when I removed `--headless` argument. Have you any idea what causes this error? ![Screenshot from 2023-11-07 14-59-36](https://private-user-images.githubusercontent.com/63507675/281045488-98a0a5af-cceb-4830-8da8-a3a6486b7de0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODU1OTYsIm5iZiI6MTcxMjg4NTI5NiwicGF0aCI6Ii82MzUwNzY3NS8yODEwNDU0ODgtOThhMGE1YWYtY2NlYi00ODMwLThkYTgtYTNhNjQ4NmI3ZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAxMjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NWE4MGQ2ZGY1N2E0YjJkNDk5ZDMzOTk2MmQ4NDc4NjQ3YmI5MGZlZmMxZDU0N2VjM2U4MjYzNjEwYWQwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SVzNvdQJo-NxP0qZQjSj14DkNCmukaMdqCYiQ_0o1Hw)
> 
> How did you solve the problem of “no qt platform could be initialized” when remove “--headless” in script.I encountered the same error information like you photo.

I have solved this problem refer this text [https://askubuntu.com/questions/308128/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without](url)

**Comment by SFGHRT** [comment]
Traceback (most recent call last):
  File "scripts/visualize-SMPL.py", line 121, in <module>
    smpl_layer = SMPLLayer(model_type='smpl',
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/aitviewer/models/smpl.py", line 66, in __init__
    self.bm = smplx.create(
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/smplx/body_models.py", line 2412, in create
    return SMPLX(model_path, **kwargs)
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/smplx/body_models.py", line 975, in __init__
    assert osp.exists(smplx_path), 'Path {} does not exist!'.format(smplx_path)
AssertionError: Path ../data/smplx_models does not exist!
@tijiang13   There is no download or file description for this. Can you provide an explanation or explain it? How should we deal with this problem?

**Comment by SFGHRT** [comment]
> The aitviewer needs to be configured separately.

The aitviewer needs to be configured separately. what does this mean？
