### ISSUE TITLE
Result blurring?

### ISSUE THREAD

**Issue by mengcius** [tijiang13/InstantAvatar#24]
Hello, why my training results are blur?

![0](https://github.com/tijiang13/InstantAvatar/assets/46582759/822c286b-6207-4259-9e36-5807c1848467)

![aist_demo](https://github.com/tijiang13/InstantAvatar/assets/46582759/f3ff4ade-d0e4-43a4-bfdd-3829ac867c53)

**Comment by tijiang13** [comment]
Hi,

Could you provide more details regarding the specific configuration, e.g. the output of the pip list command?

Best,
Tianjian

**Comment by tijiang13** [comment]
Hi,

I test quickly on torch 1.12.1 and the results look ok on my side:

![image](https://github.com/tijiang13/InstantAvatar/assets/15152165/a9e353ad-a6e1-4478-a8b5-c28e3da596cd)

And my configuration:
```
pytorch-lightning        1.5.7
pytorch3d                0.7.2
tinycudann               1.6
torch                    1.12.1+cu116
torchmetrics             0.11.4
torchvision              0.13.1+cu116
```

Best,
Tianjian
