### ISSUE TITLE
Demo code on `female-3-casual` turns out all black

### ISSUE THREAD

**Issue by hangg7** [tijiang13/InstantAvatar#25]
Hi Tianjian,

Thanks for releasing your code! I am playing around with it and trying out demo code on `female-3-csual`. Using the latest commit, I got all black results with the following command (following your demo script):
```bash
python train.py \
    --config-name demo \
    dataset=peoplesnapshot/female-3-casual \
    experiment=demo
```
![image](https://github.com/tijiang13/InstantAvatar/assets/10098306/53714d6a-c45c-4f98-90a8-a6e1f00eb922)

Same command for `male-3-casual` gives reasonable results
![image](https://github.com/tijiang13/InstantAvatar/assets/10098306/4395741b-81bb-486b-a045-ea5f7dead83f)

Could you please confirm?

Best,
Hang

**Comment by tijiang13** [comment]
Hi Hang,

Thank you for informing me about this. I encountered a similar issue in the past, which was resolved by increasing the weight of the noise from 0.1 to 1. However, it appears that this solution may not be universally applicable in all cases.

In a similar fashion, you can adjust the noise by increasing it to 10 in the corresponding section [here](https://github.com/tijiang13/InstantAvatar/blob/master/instant_avatar/models/DNeRF.py#L77). Here is what I got after that:

![image](https://github.com/tijiang13/InstantAvatar/assets/15152165/b4477a00-c030-4506-9762-4d6b9d701554)

Best, Tianjian

**Comment by hangg7** [comment]
Hi Tianjun, thanks for you tips! It indeed helps. Do you have any idea of what is the issue here? Do you think it is a problem with rendereing or the SNARF warping?

**Comment by tijiang13** [comment]
Hi Hang,

I suspect it has something to do with the initialization of the network and the use of ReLU activation functions. When encountering a black pixel, the network faces a dilemma: it can either predict black color directly or predict a density of zero to minimize color loss. However, with ReLU activation functions, there is a possibility that a neuron can become 'stuck' in latter case.

Best,
Tianjian

**Comment by hangg7** [comment]
Interesting! I am not sure I fully follow: I thought here we have random background color compositing to mitigate this issue. Also, if that's the case it seems like a general issue with ReLU-based NeRFs, which I personally have not seen before. Thanks for your thoughts!

**Comment by tijiang13** [comment]
> Interesting! I am not sure I fully follow: I thought here we have random background color compositing to mitigate this issue. Also, if that's the case it seems like a general issue with ReLU-based NeRFs, which I personally have not seen before. Thanks for your thoughts!

Indeed, I adoptedrandom background color to mitigate this problem, which does help to some extent. However, we only do that for background, not for foreground, so it's not particularly helpful especially we sample mostly on foreground. I have never experienced similar problem before either, but most NeRF datasets don't have a almost black foreground either.

Best, Tianjian

**Comment by hangg7** [comment]
Thanks! Closing this
