### ISSUE TITLE
Questions about processing the Neuman dataset

### ISSUE THREAD

**Issue by litchisea** [tijiang13/InstantAvatar#30]
Thank you for your outstanding work! I have a question about processing the Neuman dataset. When I run bash scripts/custom/process-sequence.sh ./data/custom/seattle neutral, the error is as follows.
<img width="587" alt="a452784c3165308dad9c8209897335a" src="https://github.com/tijiang13/InstantAvatar/assets/106635715/cc50e343-bfdd-4bb1-8bfc-4176903ce75f">

**Comment by tijiang13** [comment]
Hi litchisea,

Thanks for pointing this out. I think a recent update in AITViewer has unfortunately broken something. However this is only for visualize the fit SMPL so it's safe to ignore this issue. Alternatively, I think visualize without headless mode should work fine. You can do that by removing  `-headless` from that command.

Thanks for bringing this to my attention. It appears that a recent update in AITViewer has broken something. However, this should only affect the visualization of the SMPL and can be safely ignored. Alternatively, you can try visualizing without the headless mode, which should work without any issues. To do this, simply remove the -headless parameter from the command.

Best, Tianjian
