### ISSUE TITLE
ValueError: mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed: use default_factory

### ISSUE THREAD

**Issue by msverma101** [tijiang13/InstantAvatar#32]
can you please tell me why i am getting this error i wanted to run the demo

**Comment by msverma101** [comment]
this error was coz of wrong function being imported 
from pytorch_lightning.profiler import AdvancedProfiler


from pytorch_lightning.profilers import AdvancedProfiler

**Comment by tijiang13** [comment]
Thanks for the feedback.
