### ISSUE TITLE
pytorch_lightning  profiler

### ISSUE THREAD

**Issue by msverma101** [tijiang13/InstantAvatar#33]
ModuleNotFoundError: No module named 'pytorch_lightning.profiler'

the error is coz you have used a wrong profiler 
its 
*from pytorch_lightning.profilers import AdvancedProfiler*

profilers and not profiler

**Comment by tijiang13** [comment]
Hi,

It seems that you are using a different version of PyTorch-Lightning. In this project, we assume the use of version 1.5.7, and it's possible that the APIs may have undergone changes in later versions. 

Best,
Tianjian
