### ISSUE TITLE
InstantiationException("Error locating target 'instant_avatar.utils.loss.NGPLoss', see chained exception above.\nfull_key: opt.loss")

### ISSUE THREAD

**Issue by msverma101** [tijiang13/InstantAvatar#35]
bash ./bash/run-demo.sh 
Global seed set to 42
Switch to /home/sneha/Downloads/git/thesis/InstantAvatar/outputs/peoplesnapshot/demo/male-3-casual
[train] Loading from /home/sneha/Downloads/git/thesis/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_train.npz
[val] Loading from /home/sneha/Downloads/git/thesis/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_val.npz
[test] Loading from /home/sneha/Downloads/git/thesis/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_test.npz
[2023-07-10 11:18:32,212][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpz64cvx2x
[2023-07-10 11:18:32,213][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpz64cvx2x/_remote_module_non_scriptable.py
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Error in call to target 'instant_avatar.models.DNeRF.DNeRFModel':
InstantiationException("Error locating target 'instant_avatar.utils.loss.NGPLoss', see chained exception above.\nfull_key: opt.loss")
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Global seed set to 42
Switch to /home/sneha/Downloads/git/thesis/InstantAvatar/outputs/peoplesnapshot/demo/male-3-casual
[train] Loading from /home/sneha/Downloads/git/thesis/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_train.npz
[val] Loading from /home/sneha/Downloads/git/thesis/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_val.npz
[test] Loading from /home/sneha/Downloads/git/thesis/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_test.npz
[2023-07-10 11:18:40,983][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpvaffxey8
[2023-07-10 11:18:40,985][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpvaffxey8/_remote_module_non_scriptable.py
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Error in call to target 'instant_avatar.models.DNeRF.DNeRFModel':
InstantiationException("Error locating target 'instant_avatar.utils.loss.NGPLoss', see chained exception above.\nfull_key: opt.loss")
full_key: model

While running the demo i am getting this error can you please tell me where is NGPloss should be ?

**Comment by tijiang13** [comment]
Hi,

Thanks for letting me know. I have ported the lpips function [here](https://github.com/tijiang13/InstantAvatar/blob/master/third_parties/lpips/lpips.py) so installing lpips shouldn't be necessary. But it looks like there are some mistakes in the porting. Now this should be resolved with the newest commit.

Best,
Tianjian
