### ISSUE TITLE
High-resolution Avatar

### ISSUE THREAD

**Issue by Bai426** [tijiang13/InstantAvatar#36]
Hi, there, thank you very much for this great contribution. I am wondering whether there is a way to obtain a higher-resolution avatar (e.g., two times of current one). Please let me know your thinking. Thanks!

Best,
Mike

**Comment by tijiang13** [comment]
Hi Yongsheng,

As shown [here](https://github.com/tijiang13/InstantAvatar/blob/master/novel_view.py#L28) we specify the resolution of the images generated.

Best, Tianjian

**Comment by Bai426** [comment]
Got it, thank you very much!

Best,
Mike
