### ISSUE TITLE
question about animation

### ISSUE THREAD

**Issue by mit10000** [tijiang13/InstantAvatar#37]
Thanks for the wonderful job and codes!
You mentioned 
And you can animate the avatar easily:

Could you please let me know how to animate the avatar?
Thanks!

**Comment by tijiang13** [comment]
Hi Mit10000,

You can animate it by providing some motion sequences (in SMPL's format), as shown [here](https://github.com/tijiang13/InstantAvatar/blob/master/bash/run-demo.sh#L6)

Best, Tianjian
