### ISSUE TITLE
Questions about data preprocessing

### ISSUE THREAD

**Issue by litchisea** [tijiang13/InstantAvatar#38]
Hello! I would like to ask if you have run the Neuman code of the data set you used. If I want to apply the Segmentanything you used to the extraction mask in Neuman's data preprocessing, how should I deal with it? I see that it is generated in your code The masks and masked_images only have pictures, but there are other files such as output.pkl files in Neuman, can you tell me how to deal with them?thanks!

**Comment by tijiang13** [comment]
Hi litchisea,

Sorry but I haven't checked the data processing pipeline of Neuman closely.

Best, Tianjian
