### ISSUE TITLE
How is the animation-driven npz file generated?

### ISSUE THREAD

**Issue by JACKYLUO1991** [tijiang13/InstantAvatar#4]
I am interested in this repo, what project is the npz file based on to generate it?

**Comment by tijiang13** [comment]
Hi,

The animation is from the AIST dataset.

Best,
Tianjian

**Comment by JACKYLUO1991** [comment]
@tijiang13 Can you tell me why the characters don't have hands after training? 
![image](https://user-images.githubusercontent.com/21237742/233832521-4a63076f-2214-4ada-ac0f-59f76ec98c36.png)

**Comment by tijiang13** [comment]
Hi,

I have not come across the specific issue mentioned personally, so it's difficult to provide an accurate assessment without access to the data.

However, based on speculation, it is possible that the problem could be attributed to motion blur. This can be observed in the image provided from the Neuman dataset, where the hand appears transparent, potentially leading to failure in video matting.
 
<img width="459" alt="image" src="https://user-images.githubusercontent.com/15152165/233833089-05579296-f470-43ba-8478-3b22cb00045a.png">

Best,
Tianjian

**Comment by JACKYLUO1991** [comment]
Thanks, I'll try it.

**Comment by maocaixia** [comment]
> Hi,
> 
> The animation is from the AIST dataset.
> 
> Best, Tianjian

Hi, I found that the AIST dataset is full of video and audio files. Are these 3D actions extracted from the video by yourself? How did you extract them? Thanks！ @tijiang13
