### ISSUE TITLE
Can we test own data ? 

### ISSUE THREAD

**Issue by NaToh5** [tijiang13/InstantAvatar#41]
Hi, thank you for sharing your work. 

My question is that can I test my own custom 2D image or video in your model ? 

And also how did you extract the texture from the input image or video? I am finding out how to extract the texture from 2D image and apply it on a 3D SMPL obj. Could you give me some advice about that? 

Thanks,

**Comment by tijiang13** [comment]
Check https://github.com/tijiang13/InstantAvatar#play-with-your-own-video

Best, Tianjian
