### ISSUE TITLE
Could the code run on multi gpus?

### ISSUE THREAD

**Issue by yf1019** [tijiang13/InstantAvatar#42]
Hi tianjian,

Really appreciate your work as Fast-Snarf and InstantAvatar. I'm trying to involve this module into my project but I found it failed to run on the multi gpus. May I ask how can I use it (especially fast-snarf) on multi gpus setting?

Thank you so much.

**Comment by yf1019** [comment]
Hi Thanks for your reply. 

However, I test the multi-gpu setting and carefully check the tensor device. It still gives error like cuda memory faulty on fast-snarf.  I'm not sure the reason.

**Comment by tijiang13** [comment]
That's weird. Usually illegal memory accesses are caused by tensors originating from different devices (if it worked on single GPU). However, if that possibility has already been ruled out, then it's difficult for me to pinpoint the cause.

Best, Tianjian

**Comment by yf1019** [comment]
Hi Tianjian,

No problem. Thanks so much for your help.
