### ISSUE TITLE
SMPL-X support

### ISSUE THREAD

**Issue by KosukeFukazawa** [tijiang13/InstantAvatar#45]
Hello, thank you for sharing your work! 
I would like to use SMPL-X instead of SMPL for detailed representation of faces and hands. I have already finished parameter estimation for SMPL-X. Is it possible to support SMPL-X with FastSNARF deformation?
If so, how should I change the code?

**Comment by tijiang13** [comment]
Hi Kosuke,

It's possible. You can refer to https://github.com/Skype-line/X-Avatar for details.

Best, Tianjian

**Comment by KosukeFukazawa** [comment]
Thank you for your reply.
I would like to use multi-view videos to avoid occlusion. Is it possible to extend to multiple-view setting by simply changing the input on InstantAvatar?

**Comment by KosukeFukazawa** [comment]
Thank you very much! I'll try it.
