### ISSUE TITLE
Bug in preprocess custom videos

### ISSUE THREAD

**Issue by Darius-H** [tijiang13/InstantAvatar#48]
https://github.com/tijiang13/InstantAvatar/blob/4348c1e5a38627a8096d288072896e281577d4f5/scripts/custom/run-sam.py#L26C5-L26C5
The former is "masked_sam_images", but the last line in replace function is "masked_sam_images"

**Comment by tijiang13** [comment]
Duplicated https://github.com/tijiang13/InstantAvatar/issues/49
