### ISSUE TITLE
Bug in preprocessing custom videos

### ISSUE THREAD

**Issue by Darius-H** [tijiang13/InstantAvatar#49]
https://github.com/tijiang13/InstantAvatar/blob/4348c1e5a38627a8096d288072896e281577d4f5/scripts/custom/run-sam.py#L26C1-L37C68
dirname in makedirs is "masks_sam_images" but the last line in replace is "masked_sam_images".

And i found this segmentation model struggles in segmenting human hand from the background. Maybe adding hand keypoints will be better.

**Comment by tijiang13** [comment]
Hi,

Thanks for bringing this up. I used to store the masked images in the `masks_sam_images` folder to verify if the segmentation is correct. As we are not using these images for training it shouldn't influence the results.

Regarding the keypoints, yes, we can actually switch to that easily by adding `--hand` [here](https://github.com/tijiang13/InstantAvatar/blob/master/scripts/custom/run-openpose-bin.sh#L25).

Best, Tianjian
