### ISSUE TITLE
How to save the textured mesh?

### ISSUE THREAD

**Issue by autowo** [tijiang13/InstantAvatar#5]
Looking forward to your early reply.

**Comment by tijiang13** [comment]
Hi,

You can check out `instant_avatar/utils/marching_cube.py`

Best,
Tianjain

**Comment by Yuanhong200727** [comment]
@tijiang13 Sorry,I still don't know how to export a textured mesh using marching_cube.py.Can you give me the detailed steps to achieve it?Thanks so much!
