### ISSUE TITLE
Running on ZJU dataset

### ISSUE THREAD

**Issue by jamesyoung0623** [tijiang13/InstantAvatar#50]
Hello, 
Thank you for sharing your work!
I am trying to run your training code on the ZJU dataset, but here's my result.
![imageData](https://github.com/tijiang13/InstantAvatar/assets/55226860/52332ce2-4008-4760-89bb-097a35f07c49)

If you have experimented with the ZJU dataset would you share your experiment?
Thanks a lot!

**Comment by tijiang13** [comment]
Hi James,

Thank you for sharing the results. Although I haven't yet tested the model on the ZJU dataset, given that they have calibrated cameras and poses estimated from a multi-view setup this dataset might be somewhat easier to work with compared to the Neuman dataset.

Regarding the results, I remember that the ZJU dataset uses a modified version of the SMPL model, whereas we adhered to the standard SMPL definition. Did you convert the SMPL parameters accordingly? You can easily verify the SMPL parameters using the visualization script available [here](https://github.com/tijiang13/InstantAvatar/blob/master/scripts/visualize-SMPL.py)."

Best, Tianjian

**Comment by jamesyoung0623** [comment]
Thank you for pointing out the difference and the useful script.
I have another question about anim_nerf_train.npz, anim_nerf_val.npz, and anim_nerf_test.npz.
I notice that they have 114, 1, and 55 frames respectively.
Are these frames randomly sampled from the origin 690 frames?

**Comment by tijiang13** [comment]
Hi James,

1. They are sampled in equal steps. The length varies as the original videos have different lengths.
2. it's the global translation of SMPL.

Best, Tianjian

**Comment by jamesyoung0623** [comment]
Hi Tianjian,
Thank you for your explanation.
This is my current visualization.

https://github.com/tijiang13/InstantAvatar/assets/55226860/47e85a61-c4ff-4015-a704-b5790a680487

It seems like the rotation of ZJU dataset is incompatible with yours.
Would you know how to rotate the pose parameters?
Thank you!

**Comment by tijiang13** [comment]
Hi James,

You can check [this](https://github.com/zju3dv/EasyMocap/blob/master/doc/02_output.md#attention-for-smplsmpl-x-users) for the conversion.

Best, Tianjian
