### ISSUE TITLE
Question about pose preprocess.

### ISSUE THREAD

**Issue by GostInShell** [tijiang13/InstantAvatar#51]
Hi. Thanks for contributing the code of your amazing work!

I have some questions about the data. I notice that the pose data `poses/anim_nerf_{split}.npz` are different from the original pose data `poses.npz`. Are these human poses refined? Could you kindly provide the code please? Thanks a lot!

**Comment by tijiang13** [comment]
Hi,

For experiments in PeopleSnapshot we used the poses refined by our baseline (Anim-NeRF) as we cannot optimise shapes with FastSNARF.

Best, Tianjian

**Comment by xiezhy6** [comment]
> Hi,
> 
> For experiments in PeopleSnapshot we used the poses refined by our baseline (Anim-NeRF) as we cannot optimise shapes with FastSNARF.
> 
> Best, Tianjian

I found the training time of Anim-NeRF is quite long... Could you please share me the other refined poses for the data in PeopleSnapshot?

 Best wishes!
