### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by vrahnos3** [tijiang13/InstantAvatar#52]
Hello, thanks for the great work, 
after running the commad  
```python
bash ./bash/run-demo.sh
``` 
everything seems good but nothing to visualize. 
![asd](https://github.com/tijiang13/InstantAvatar/assets/63507675/9a8cc02a-35c5-47aa-ac63-8ccbdde25934)
Am I doing something wrong or do I need to do anything else to visualize the avatar?
Thanks!

**Comment by Net-Maker** [comment]
Bro, you should find the result in outputs/people-snapshot/demo/annimatoin

**Comment by vrahnos3** [comment]
Thanks for your reply. I am trying to train my own data but I a bit confused. Can somebody explain the exact steps to preprocess data and train?
Thanks

**Comment by vrahnos3** [comment]
@Net-Maker Hello, actually in outputs/people-snapshot/demo/annimation/aist_demo there is a set of rendered frames. Is this the result that instant avatar provides? 
Also do you know how can I generate something like this gif in ReadMe? 
![male-3-casual](https://github.com/tijiang13/InstantAvatar/assets/63507675/97ba5562-fab7-44d1-94d1-acba9cced536)
I cant understand the usage of animate.py if only frames are provided as output.

**Comment by Net-Maker** [comment]
novel_view.py should generate this gif. The outputs contains all pictures you need if you run the run-Neuman-demo without any problem.So I guess you have something wrong with your code.

**Comment by tijiang13** [comment]
Hi Panos,

As suggested by Net-Maker I create the gif using imageio.

```
imageio.mimsave(f"{folder}/../{animation}.gif", imgs, fps=30)
```

Best, Tianjian
