### ISSUE TITLE
Error when increasing batch size

### ISSUE THREAD

**Issue by herybala** [tijiang13/InstantAvatar#55]
I saw we get error when increasing batch size in dataloader

**Comment by tijiang13** [comment]
Hi Herybala, 

Yes, in the code, we assume the batch size to be 1 (which means we train with 1 frame at a time). However, you can increase the number of pixels you want to sample like in [here](https://github.com/tijiang13/InstantAvatar/blob/master/confs/sampler/patch.yaml#L3) (4K by default)

Best, Tianjian

**Comment by herybala** [comment]
Hello,
Also when setting sampler to edge i got the following error:

hydra.errors.ConfigCompositionException: Could not override 'sampler.dilate'.
To append to your config use +sampler.dilate=8

**Comment by tijiang13** [comment]
Hi Herybala,

From the error it appears that you are trying to pass parameters that EdgeSampler doesn't recognise to it (dilate in this case). If you want to switch sampler you can either:

1. change "patch" to "edge" [here](https://github.com/tijiang13/InstantAvatar/blob/master/confs/demo.yaml#L5)
2. or specify in the command line like "python train.py sampler=edge"

Best, Tianjian
