### ISSUE TITLE
Error in scripts/visualize-SMPL.py

### ISSUE THREAD

**Issue by LuckyOne09** [tijiang13/InstantAvatar#6]
Hello,

Firstly, I would like to express my appreciation for your amazing work. I have encountered a small error while processing the scene 'Seattle' in the 'Neuman' dataset using the 'scripts/custom/process-sequence.sh' script. I believe this bug is related to 'aitviewer', as shown in the attached image:

![image](https://user-images.githubusercontent.com/38714962/233442757-bcffaa2e-9158-4f6a-947b-ee64763ea6c7.png)

I have dug into the source code of `aitviewer`, but I still don't know what might be causing the 'frames' variable to equal zero.

Thank you for your attention.

**Comment by LuckyOne09** [comment]
I resolve the problem by adding these two lines of code at the beginning, but I'm not entirely sure if this is the correct approach:

    from aitviewer.configuration import CONFIG as C
    C.update_conf({"playback_fps": 1})


By the way, I would like to ask if anyone knows of a convenient way to visualize SMPL mesh in 3D space since it is common that 3d fitting is not correct even if projection of the smpl mesh is perfect

**Comment by tijiang13** [comment]
I also looked into the code, and it seems there can be a bug when playback_fps is too large. So using a lower playback_fps is the right way to go.
 
Anyway, good to hear that you have solved the problem.
