### ISSUE TITLE
Error on process-sequence.sh

### ISSUE THREAD

**Issue by vrahnos3** [tijiang13/InstantAvatar#60]
Hello, thanks for the great work.
First I want to mention an error in `process-sequence.sh` file. In thιs line https://github.com/tijiang13/InstantAvatar/blob/4348c1e5a38627a8096d288072896e281577d4f5/scripts/custom/process-sequence.sh#L46 you run `visualize-SMPL.py` whith argument `--pose $path/pose_optimized.npz` but the file that is created is named 
`pose**s**_optimized.npz`. Maybe many people trying to run this script and occurs other errors that caused because poses can't be loaded. 
Secondly, even when I fixed it, the error with `_proc` still exists :
![Screenshot from 2023-11-08 12-15-35](https://github.com/tijiang13/InstantAvatar/assets/63507675/6e1df0ac-e190-4c5d-93a0-1149fc03dc83)
I tried even to run it without `--headless` arg as mentioned in #21 and the result was that: 
![Screenshot from 2023-11-08 12-19-06](https://github.com/tijiang13/InstantAvatar/assets/63507675/dcb715f4-5f45-4190-896e-2aa547a27f99)
![Screenshot from 2023-11-08 12-19-30](https://github.com/tijiang13/InstantAvatar/assets/63507675/7431a5e8-7d1e-4c55-bdf3-4bbc104eadb7)
Anyone know how to solve this?

**Comment by vrahnos3** [comment]
I solved it just increasing the number of fps in this command 
https://github.com/tijiang13/InstantAvatar/blob/4348c1e5a38627a8096d288072896e281577d4f5/scripts/custom/process-sequence.sh#L46
According to this detail I managed to export the mp4 file. When I run it without `--headless` argument above error still exists.

**Comment by tijiang13** [comment]
Hi Panos,

Sorry for slow reply as I have been quite occupied recently. Regarding your question, as can be seen [here]( https://github.com/tijiang13/InstantAvatar/blob/master/scripts/custom/refine-smpl.py#L267) the `pose_optimized.npz` should be generated automatically before. If you can't find that file, please double-check if previous scripts are executed smoothly.

For headless mode I guess it's a separate issue. I'd suggest creating a clean virtual environment and checking if the problem is persistent.

Best, Tianjian

**Comment by vrahnos3** [comment]
> Hi Panos,
> 
> Sorry for slow reply as I have been quite occupied recently. Regarding your question, as can be seen [here](https://github.com/tijiang13/InstantAvatar/blob/master/scripts/custom/refine-smpl.py#L267) the `pose_optimized.npz` should be generated automatically before. If you can't find that file, please double-check if previous scripts are executed smoothly.
> 
> For headless mode I guess it's a separate issue. I'd suggest creating a clean virtual environment and checking if the problem is persistent.
> 
> Best, Tianjian

All scripts running as well, I just mentioned that the file that is created is named `poses_optimized.npz` and in file process-sequence.sh you called it as `pose_optimized.npz` (without an **s** on the end of word pose.

**Comment by tijiang13** [comment]
Hi vrahnos3, 

Good catch,  I might change it without realizing that 🥲 Thanks a lot!

Best, Tianjian

**Comment by tijiang13** [comment]
Now it should be fixed with ed554edd13876aa84d1bf169760bf64e51cf09fb

Thanks again for letting me know!

Best, Tianjian
