### ISSUE TITLE
Question about the generated near far in Snarf_deformer.

### ISSUE THREAD

**Issue by zhao-yiqun** [tijiang13/InstantAvatar#64]
Hi 

thanks for your code releasing,

I have some questions about your code implementation here. [near, far](https://github.com/tijiang13/InstantAvatar/blob/master/instant_avatar/deformers/snarf_deformer.py#L95-L103)

I wonder why the near/far are generated from the norm of ray_o(for both training code and inference code)? I can not fully understand this, and hope you can help me about this.

(Based on my initial understanding, the near plane should be the nearest point from human body, and the far plane should be the farest plane that can fully cover the human body)

rays.o is the camera origin in smpl-coordinate, but, why do you set the torch.norm(rays.o) -1 for the near plane?

Thanks in advance

**Comment by tijiang13** [comment]
Hi Yiqun,

Here we only need a rough estimation of the near and far plane. We can definitely make it the distance between nearest point from human body and camera but it might be a bit slower to calculate that.

Best, Tianjian

**Comment by zhao-yiqun** [comment]
Thanks for your kind reply,

Now I understand that.

Bests, Yiqun
