### ISSUE TITLE
Question about optimized body pose

### ISSUE THREAD

**Issue by TohnoYouki** [tijiang13/InstantAvatar#65]
Thanks for your excellent work. I found that there is a significant difference in the results without provided optimized poses in peoplesnapshot dataset. I tried to optimize SMPL parameters in advance with fit.py following the procedure in run-neuman-demo.sh but  it didn't make any difference. So how can I train to get the optimized poses which are same to your provided ? Thanks.

**Comment by tijiang13** [comment]
Hi TohnoYouki,

We obtained the 'optimized poses' by refining the poses provided by PeopleSnapshot, which may contain noise in foot estimation. However, if you have already executed the fit.py script on the raw data beforehand, the results should not vary significantly. It would be beneficial if you could provide screenshots along with the scripts you are using.

Best, Tianjian
