### ISSUE TITLE
openpose.bin

### ISSUE THREAD

**Issue by choos11** [tijiang13/InstantAvatar#76]
CURRENT_DIR=$(pwd)  
cd $OPENPOSE_PATH  
./build/examples/openpose/openpose.bin \ 
  --image_dir $IMAGE_FOLDER \  
  --display 0 \  
  --write_json $IMAGE_FOLDER/../openpose_json/ \ 
  --write_images $IMAGE_FOLDER/../openpose_output/ \  
  --write_images_format jpg \  
  --render_pose 1 \  
  --render_threshold 0.5 \  
  --number_people_max 1 \  
  --model_pose BODY_25  
cd $CURRENT_DIR  
请问这里面的openpose.bin文件是自己写的还是openpose里面自带的，为什么我编译之后没有找到这个可执行文件

**Comment by tijiang13** [comment]
choos11你好，

这是Openpose的可执行文件，编译Openpose后就会出现在build文件夹中。参见Openpose的[文档](https://github.com/CMU-Perceptual-Computing-Lab/openpose?tab=readme-ov-file#quick-start-overview)。

祝好。

**Comment by choos11** [comment]
好的谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tijiang13/InstantAvatar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月2日(星期五) 凌晨5:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tijiang13/InstantAvatar] openpose.bin (Issue #76)





 
choos11你好，
 
这是Openpose的可执行文件，编译Openpose后就会出现在build文件夹中。参见Openpose的文档。
 
祝好。
