### ISSUE TITLE
how to get openpose.json

### ISSUE THREAD

**Issue by luoshuiyue** [tijiang13/InstantAvatar#77]
![1722482370029](https://github.com/user-attachments/assets/8c0a7bda-9083-4f33-8f1c-ec5dd890ae76)
What data do we need and what command do we run to get the openpose.json file

**Comment by tijiang13** [comment]
Hi luoshuiyue,

`openpose.json` contains the predictions generated by OpenPose. According to the log, it seems that the executable file for OpenPose could not be found. If you have already compiled OpenPose, you can update the path in `./scripts/custom/run-openpose-bin.sh` to the correct location.

Best, Tianjian
