### ISSUE TITLE
cd: /root/third_party/openpose-cpp/: No such file or directory

### ISSUE THREAD

**Issue by upauparuru** [tijiang13/InstantAvatar#83]
@tijiang13 
Dear author, Hello.

When I executed the following code, I encountered an error: 
`bash scripts/custom/process-sequence.sh ./data/custom/seattle neutral`

Error details: 

> /// "Running OpenPose in /content/InstantAvatar/data/custom/seattle/images
> scripts/custom/run-openpose-bin.sh: line 22: cd: /root/third_party/openpose-cpp/: No such file or directory
> scripts/custom/run-openpose-bin.sh: line 24: ./build/examples/openpose/openpose.bin: No such file or directory
> Traceback (most recent call last):
>   File "./scripts/custom/convert_openpose_json_to_npy.py", line 44, in <module>
>     convert(JSON_FOLDER, NPY_PATH)
>   File "./scripts/custom/convert_openpose_json_to_npy.py", line 11, in convert
>     for JSON_FILE in sorted(os.listdir(JSON_FOLDER)):
> FileNotFoundError: [Errno 2] No such file or directory: '/content/InstantAvatar/data/custom/seattle/images/../openpose_json/'
> Traceback (most recent call last):
>   File "scripts/custom/run-romp.py", line 5, in <module>
>     import romp
> ModuleNotFoundError: No module named 'romp'
> Refining SMPL...
> Traceback (most recent call last):
>   File "scripts/custom/refine-smpl.py", line 9, in <module>
>     from pytorch3d.renderer import (
> ModuleNotFoundError: No module named 'pytorch3d'
> Traceback (most recent call last):
>   File "scripts/visualize-SMPL.py", line 88, in <module>
>     camera = dict(np.load(f"{args.path}/cameras.npz"))
>   File "/usr/local/envs/instant/lib/python3.8/site-packages/numpy/lib/npyio.py", line 407, in load
>     fid = stack.enter_context(open(os_fspath(file), "rb"))
> FileNotFoundError: [Errno 2] No such file or directory: '/content/InstantAvatar/data/custom/seattle/cameras.npz'" ///

I thought these steps would be performed automatically, but do I need to configure these files myself? I noticed from the GitHub repository that the /third_party/openpose-cpp directory is missing. Thank you.

**Comment by NewPhrexian** [comment]
You need to compile openpose by yourself
